platform :ios, '9.0'
pod 'ADAL', '~> 2.3'
pod 'NMSSH', '~> 2.2.5'

target 'AzureIoTDevKitCompanion' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'ADAL', '~> 2.3'
  pod 'NMSSH', '~> 2.2.5'
end
